quarkus:
  smallrye-jwt:
    enabled: true

  datasource:
    devservices:
      enabled: false

    db-kind: postgresql
    username: abc
    #password: 123456
    password: somePassword
    jdbc:
      # url: jdbc:postgresql://localhost:5433/postgres
      url: jdbc:postgresql://localhost:5432/postgres
      driver: org.postgresql.Driver

  hibernate-orm:
    database:
      generation: update
    log:
      sql: true

smallrye:
  jwt:
    path:
      groups: "roles"